### ISSUE TITLE
[Feature Request] Support Live Preview Mode

### ISSUE THREAD

**Issue by damywise** [nicojeske/mousewheel-image-zoom#10]

**Comment by KuiyueRO** [comment]
It is supported, but only wiki Links is supported

**Comment by nicojeske** [comment]
In my own test vault everything works as expected in live preview mode. Local files as well as files in the web do work without problems.

Could you provide an example that is not working?

**Comment by csss1234** [comment]
With my install, in either live preview or legacy preview, I can only get the plugin to adjust once. It works once, sets the image at [[image name | 300]] or whatever number, and never adjusts again. 

Ive disabled all other community plugins, disabled all themes and custom CSS. Tried on a new vault. Disabled other software that I know looks out for modifiers (better touch tool, keyboard maestro )

I tried it on a recent version 13.x and am now trying on 14.4 with same results.
Using Mousewheel version 1.0.13
