### ISSUE TITLE
[Feature Request] Allow to use caption text when using this addon

### ISSUE THREAD

**Issue by midvok** [nicojeske/mousewheel-image-zoom#11]
First, thank you for this very useful addon for resizing images.

I have one idea for improvement when you also use also the addon for displaying captions (https://github.com/bicarlsen/obsidian_image_caption).

Currently, I can specify both caption and size as follows (which perfectly works in Obsidian):
```
![[image.jpg|"Caption"|400]]
```
But when I start using the Image Zoom addon, it inserts a new value before the caption (which seems to be ignored by Obsidian and only the last value is used).
```
![[image.jpg|200|"Caption"|400]]
```
So, my proposal is to detect and change the image size value as the last element instead of inserting a new value. Does it make sense?

**Comment by nicojeske** [comment]
Support should be added in the newest update :)

**Comment by midvok** [comment]
Thank you very much for the update, I just tested it and it works perfectly :)
