### ISSUE TITLE
支持markdown超链接

### ISSUE THREAD

**Issue by irrealizable** [nicojeske/mousewheel-image-zoom#13]
目前对于本地引用的图片，仅支持wiki链接，不支持markdown标准语法超链接
for locally images，only wiki links are supported，markdown standard syntax links are not supported

**Comment by irrealizable** [comment]
https://help.obsidian.md/How+to/Format+your+notes#Resizing+images
like this，
Example of this above image resized to 100 pixels wide:
![Engelbart|100](https://history-computer.com/ModernComputer/Basis/images/Engelbart.jpg)

**Comment by mwolter805** [comment]
Hello, is there anything that can be done about this? It would be great if this plugin also supported images using markdown standard syntax.

**Comment by irrealizable** [comment]
> Hello, is there anything that can be done about this? It would be great if this plugin also supported images using markdown standard syntax.

no, I have no solution for this question. now Ichange the css to make the image shrink 30% ,and I use the plugin "image toolkit" to view the images

**Comment by nicojeske** [comment]
Fixed in version 1.0.14.
