### ISSUE TITLE
When using callout many times, it can not work

### ISSUE THREAD

**Issue by bitons** [nicojeske/mousewheel-image-zoom#14]
> [!hint]- hint 1
>![[1.6]]

This "1.6" file includes an image with a callout. In the callout block I only see the image but can not enlarge it.

and if the callout with a ''-'' like this

>[!hint]- 
>image

Holding down left alt does not work too.

**Comment by nicojeske** [comment]
The plugin modifies the image size, but this causes the callout to reload, which results in it being closed again. Unfortunately, I don't believe there is a way to avoid this issue.
