### ISSUE TITLE
FR - Ability to zoom into mermaid flow charts 

### ISSUE THREAD

**Issue by johans3** [nicojeske/mousewheel-image-zoom#15]
By default, we aren't able to zoom into mermaid flow charts.
That's a bummer because mermaid is easy to use once you get used to and therefore, you start building bigger and better flow charts. The bigger flow charts, the less mermaid is readable. There is no zoom or pan to view big charts 

I think this mouse wheel plugin should have offer more functionality wherever needed

**Comment by nicojeske** [comment]
I do not think that this functionality is in the scope of this plugin. There only seem to exist workarounds for resizing mermaid charts via CSS hacks ([Obsidian Forum](https://forum.obsidian.md/t/ability-to-resize-and-align-mermaid-diagrams/7019/22?page=2)).
