### ISSUE TITLE
Does not resize the image

### ISSUE THREAD

**Issue by javiavid** [nicojeske/mousewheel-image-zoom#16]
The plugin changes the number at the end of the link, but the image does not change.
If you change the number at the beginning it works correctly.

Can the plugin change the number at the beginning of the link?

https://user-images.githubusercontent.com/7627504/191714625-a1b74ab8-c000-46dd-96da-7e783d4356b4.mp4

Obsidian 0.16.3
Plugin 1.0.13

**Comment by nicojeske** [comment]
Fixed in version 1.0.14.
