### ISSUE TITLE
hope it can work with the excalidraw!

### ISSUE THREAD

**Issue by Simsim20212021** [nicojeske/mousewheel-image-zoom#17]
![image](https://user-images.githubusercontent.com/94425879/210594087-2c1addc1-6f90-4fa2-9431-5d1e0a1292b6.png)
![image](https://user-images.githubusercontent.com/94425879/210594200-81f3b323-40aa-443a-ac5c-ac9fa437e114.png)
it is same for the way to set the size between .png and .excalidraw.
may it can also work with the excalidraw?
but current version does not work, hope it in the next version!

**Comment by nicojeske** [comment]
Thanks to #19 this should be fixed.
