### ISSUE TITLE
Doesn't work with web sources

### ISSUE THREAD

**Issue by NeighNeighNeigh** [nicojeske/mousewheel-image-zoom#2]
Hey, neat plugin! just tried it today and sadly it doesn't work for embedded images from the web. For example, doesn't work with this code:

```![|500](https://imgaz2.staticbg.com/thumb/large/oaupload/banggood/images/58/DC/9937f2af-3de1-4fbe-8a57-37681815fe26.jpg)```

**Comment by nicojeske** [comment]
I actually never tried it with web embedded images. 

If I find the time I will look into it and keep you updated when I get it working.
