### ISSUE TITLE
add a slash before the vertical line

### ISSUE THREAD

**Issue by Mrlution** [nicojeske/mousewheel-image-zoom#23]
Thank you for providing this convenient plugin.

The syntax for tables uses vertical bar, so it is not possible to use resized images within a table. I would like to add slash before the vertical bar so that resized images can be used within the table.

for example
`![[image.png \| 100]]`

Maybe a settings option could be added to achieve this?

**Comment by nicojeske** [comment]
The plugin does already handle images in tables by automatically adding a slash before the vertical bar. Can you give me an example where this fails for you?
