### ISSUE TITLE
Does not work when the filename contains both spaces and Chinese characters.

### ISSUE THREAD

**Issue by cangjun123** [nicojeske/mousewheel-image-zoom#26]
I have found that when importing a file with both Chinese characters and spaces in the filename, the image resizing function does not work. For example: "中 文.png".

**Comment by nicojeske** [comment]
How exactly does your markdown look like? I just tested with ![[中 文.png]] and the image is resizable.

**Comment by cangjun123** [comment]
![](attachments/中%20文.png)
