### ISSUE TITLE
Open the article in a new window, the plugin does not work

### ISSUE THREAD

**Issue by jiajiala** [nicojeske/mousewheel-image-zoom#30]
When I use the Move to new window command

In the new window, the image can no longer be enlarged or reduced by the scroll wheel

**Comment by jiajiala** [comment]
It's the same under canvas

**Comment by Mideks** [comment]
Duplicate of #33 and #37. 
#33 is fixed in #40, but #37 still open...

**Comment by nicojeske** [comment]
Closed as the main issue is fixed. For progress on the Canvas issue see #37
