### ISSUE TITLE
插件无法生效，无法通过鼠标滚轮调节图片大小

### ISSUE THREAD

**Issue by HiramYang** [nicojeske/mousewheel-image-zoom#32]
Obsidian版本：1.4.13
window版本：win11

在Obsidian-编辑器-显示-文档属性 设置为源码时，插件能够正常工作。但在设置为显示时，插件就无法工作了，无法调节图片大小

此时插件能够正常工作
![image](https://github.com/nicojeske/mousewheel-image-zoom/assets/50940093/43c00f77-2331-4d08-a50f-8636124d4578)

此时插件不能正常工作
![image](https://github.com/nicojeske/mousewheel-image-zoom/assets/50940093/bbfde765-407b-4fff-90de-8f05f9bd1c42)

**Comment by Mideks** [comment]
Can't reproduce this bug.

**Comment by nicojeske** [comment]
Closed as the behaviour is not reproduceable.
