### ISSUE TITLE
Failed in canvas

### ISSUE THREAD

**Issue by dongzhonghua** [nicojeske/mousewheel-image-zoom#37]
obsidian version: v1.5.3
platform: mac

failed on canvas file

**Comment by nicojeske** [comment]
This is currently not supported and I currently do not have the resources to implement it. I will leave the issue open in the case someone wants to work on it.

**Comment by Mideks** [comment]
Lol, I wanted to do the same thing but didn't get round to doing it sooner.

**Comment by Mideks** [comment]
@nicojeske 
I seem to have misunderstood the nature of these problems..... I just realised that I may have been referring to the canvas embedded md files, where you can't resize the picture while on the canvas.

But I originally understood this problem as "there are pictures on the canvas and you can't resize them with the wheel like in md files"
Lol, and, I almost implemented that feature before I realised it might not be exactly what was meant. 

Do you think my implementation is appropriate in your plugin?

**Comment by nicojeske** [comment]
I am also not sure what behaviour @dongzhonghua means.  But currently both, zooming a directly embedded image in a canvas and zooming an image embedded in an md file that is embedded in the canvas, are not implemented. 

Feel free to work on any of those two features if you want to, I will gladly merge your PR if you find a way to implement this.

**Comment by Mideks** [comment]
@nicojeske 
In fact, I've been working on this feature for two days now, and I think I've managed to finish it by 70%. I've found a way to directly resize the nodes on the canvas, and I'm testing the work now and finalising the scaling logic while preserving the proportions...

By the way, do you think resizing should only work for pictures, or for any type of node, like videos, sounds, pdf or even md files?

**Comment by Mideks** [comment]
By the way, I opened #47 for the reason that it will not be possible to use Shift (because of horizontal scrolling) and Ctrl (because of canvas zooming) modifiers normally on canvas. So maybe it would be a good idea to enable scroll lock only when the cursor is over an element? (something like hover event)

**Comment by nicojeske** [comment]
Implemented as of #48 in 1.0.22
