### ISSUE TITLE
I can't scroll until I press alt

### ISSUE THREAD

**Issue by m-danya** [nicojeske/mousewheel-image-zoom#4]
Thank you for such a convenient plugin! But I have faced an issue: 

When I alt-tab to the obsidian, in half of cases, the plugin behaves as if I am holding the ALT button: 
- I can't scroll until I press the alt button manually
- if I scroll with the cursor being positioned on the image, it resizes

As a workaround, I wanted to suggest making users able to choose the trigger button, but **I have already found this option in the plugin settings**. 

I'll leave this issue as a hint to other users, who suffer from this :)

**Comment by nicojeske** [comment]
Hi there,

The problem was, that when tabbing out of obsidian, obsidian will not be notified when the alt key gets released.

I will address this issue in the next release coming up in a few minutes by checking if the key is really still pressed before doing the zooming.

Hopefully, that helps! ;)

**Comment by nicojeske** [comment]
Version 1.0.9 is released and you can now update using the community plugins tab in obsidian.

Feel free to reopen this issue if the problem still occurs.
