### ISSUE TITLE
Compatibility with ITS Theme image positions

### ISSUE THREAD

**Issue by AngelusDomini** [nicojeske/mousewheel-image-zoom#8]
Would be great if this plugin were compatible with the ITS image positions snippet from the [ITS Theme](https://github.com/SlRvb/Obsidian--ITS-Theme#image-positions). Currently, when using the plugin to resize an image that's using the snippet, it doesn't do anything except add another size number thingy in the link, which doesn't actually resize the image in preview.

E.g., when resizing an image with this link:
`![[image.png|ctr|525]]`

it then becomes something like this:
`![[image.png|500|ctr|525]]`
but does nothing to actually resize it in preview.

Currently, I'd have to resize the image without using the ITS position syntax thingy first and then add the desired syntax (ctr/left/right/etc) to the link.

Hope you'll consider. Thank you for this wonderful plugin!

**Comment by nicojeske** [comment]
Hello There!

The ITS position syntax should now be supported in the newest release.

If you still encounter problems feel free to reopen this Issue.

**Comment by AngelusDomini** [comment]
Hey, @nicojeske thank you so much for getting this to work! The only problem I've encountered so far is when using the plugin on images in tables, where the problem I described in my original post persists, except that the pipe `|` starts with a backslash `\` which is necessary for markdown tables, so:

`![[image.png\|ctr\|525]]` becomes `![[image.png\|500\|ctr\|525]]`

With images not using the ITS syntax, the plugin works as expected while respecting the backslash

**Comment by nicojeske** [comment]
@AngelusDomini It should now work in version 1.0.12 could you try it out and keep me updated?

**Comment by AngelusDomini** [comment]
Yep, it's working now! Thanks again so much!
